### ISSUE TITLE
Allow filtering sensitive info from messages logged

### ISSUE THREAD

**Issue by alecl** [actionably/dashbot#12]
Would be nice to support some sort of method to redact sensitive info from logging. Essentially some intermediate hook where a function could be supplied to modify the data before it goes to dashbot can accomplish this and more.

**Comment by sinned** [comment]
Interesting idea... I will log this as a feature request.

**Comment by sinned** [comment]
We have added "redact: true" as an option when invoking the NPM now! Thanks Alec!
