### ISSUE TITLE
Analytics of referrals with facebook

### ISSUE THREAD

**Issue by Dark1hp** [actionably/dashbot#13]
I have some troubles with referrals on facebook. Parameter like "ref" is defined but dashbot still does not show referrals and writes something that you can see on screenshot which I have attached.

![capture](https://cloud.githubusercontent.com/assets/11260342/26057818/d851ba16-3983-11e7-9a3e-c5963e4cbf31.PNG)

Ref link was realized by this link
https://developers.facebook.com/docs/messenger-platform/referral-params

Also I am getting all params
![7b188ebf-43cc-42cf-a2f9-9b765eb1f222](https://cloud.githubusercontent.com/assets/11260342/26057899/31c2fbd2-3984-11e7-9206-90656733c6f2.jpg)

**Comment by sinned** [comment]
Hey there.. thanks for letting us know — we're taking a look into this right away!

**Comment by lorenzhk** [comment]
Hi @sinned, i just tried and have the same symptom, do the team got any initial findings about it? Thanks!

**Comment by sinned** [comment]
Hey there.. This should actually be working now — I should have closed this issue awhile back when we fixed it.

**Comment by lorenzhk** [comment]
@sinned i'm not sured, i tried to implemented it in different ways with different bot, but after 24 hours, the report still empty and couldn't found any referrals. But i did setup the webhook to subscribe for message referrals & my m.em like with ref params, i can also see my code get the message.referral.ref has value too. Not sure why T_T

**Comment by dingledong** [comment]
Hey guys - I'm looking at referrals as well; have put in my parameters, they work and I can see them in dashbot, BUT I only get a message count per parameter, which is useless; I need to look at how many unique users are coming through my different campaigns/with different parameters. is there any way to see that? Thx in advance

**Comment by sinned** [comment]
This was fixed long ago — but, we also recently added reporting for ADS and DISCOVER_TAB — available in the "Events" report
