### ISSUE TITLE
Botkit middleware support for Facebook

### ISSUE THREAD

**Issue by houjunchen** [actionably/dashbot#2]
Hi, I currently have a facebook chatbot using botkit and would like to integrate it with dashbot. So it will be great if botkit middleware support for facebook is in dashbot's future plan.

**Comment by sinned** [comment]
Great suggestion! We added Facebook Botkit support today:
http://www.dashbot.io/sdk/facebook/botkit

Please let me know if you have any other questions, comments or feature requests.

Thanks for using Dashbot!
