### ISSUE TITLE
validation error:  {"success":false,"errors":[{"message":"unknown 'apiKey'"}]}

### ISSUE THREAD

**Issue by guillempuche** [actionably/dashbot#22]
I'm working with Bot Framework on my local host and interacting with Bot Framework Emulator

My code is:
```
const dashbot = require('dashbot')({apiKey: process.env.DASHBOT_KEY, debug: true}).generic;
[...]
// MIDDLEWARE to handle the inputs & outputs
[...]
const messageForDashbot = {
    "text": session.text, // text's message from session object
    "userId": "demo"
};
dashbot.logOutgoing(messageForDashbot);
[...]
const messageForDashbot = {
    "text": session.text,
    "userId": "demo"            
};
dashbot.logIncoming(messageForDashbot);
[...]
```

![screen shot on mar 12th at 04_23 pm](https://user-images.githubusercontent.com/3519924/37292710-c401d5ac-2611-11e8-93a6-cea7906478a4.png)

I've checked:
- Dashbot key on Dashbot's dashboard (above there is a photo) and environment variable
- JSON of object ```session.text```

But when I debug my code on my localhost Emulator, Dashbot's debbuger send me:
> validation error:  {"success":false,"errors":[{"message":"unknown 'apiKey'"}]}

What's the error?

**Comment by jhullfly** [comment]
The first line of your code should be: 

`const dashbot = require('dashbot')(process.env.DASHBOT_KEY, {debug: true}).generic;
`
