### ISSUE TITLE
support Dialogflow and Actions of Google v2

### ISSUE THREAD

**Issue by hyzhak** [actionably/dashbot#23]
Google officially released v2 of Dialog Flow and Actions of Google v2.
https://blog.dialogflow.com/post/v2-and-enterprise-edition-generally-available/

**Comment by hyzhak** [comment]
@ryanm2 is there any chance to get support of current Actions of Google v2?

**Comment by amerritt** [comment]
Hi all,

I'm sorry this wasn't responded to earlier. We do support V2. It's best to make sure you're using the latest version of our NPM. 

If you have any questions, please feel free to contact us on our support email - contact [at] dashbot 

Thanks,

Arte
