### ISSUE TITLE
generic (universal) bot (sdk) not working well with version 11.0.0?

### ISSUE THREAD

**Issue by pgoldweic** [actionably/dashbot#33]
I have attempted to upgrade to version 11.0.0 of Dashbot without making any code changes in my nodejs software (using Dashbot's node sdk). However, when inspecting the live transcripts for the bot conversations, I see that the json produced when calling 'dashbot.logOutgoing' is as follows:
{“userId”: “myuser”,
                “validation”: {
                                “success”: false,
                                “errors”: [
                                                {“message”: “invalid version ’11.0.1’”}
                                ]
                }, 
                “text”: “Some bot text here…”
}

Also, incoming messages do not appear to be logged at all (probably some other error message but it is not showing up anywhere).
Does version 11.0.0 have different coding requirements than previous versions? Please advise.

**Comment by sinned** [comment]
Aha -- thanks for reporting this. The validation error you're seeing in the transcripts is not a true validation error. We're fixing this now.
