### ISSUE TITLE
Require individual Lodash Modules instead of the Full Lodash library

### ISSUE THREAD

**Issue by rmtuckerphx** [actionably/dashbot#38]
Reduce the size of the required packages.

Instead of:
`require('lodash')`

Use a require for the individual functions needed:
`require('lodash.get')`
...

Here is a list of all lodash function used in this project:
- assign
- clone
- cloneDeep
- each
- find
- get
- has
- indexOf
- isArray
- isArray
- isFunction
- isObject
- isObjectLike
- isString
- map
- merge
- set

**Comment by shotamakino** [comment]
hey @rmtuckerphx , we're looking into updating much of this library - we will incorporate these changes there.
