### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by mayrbenjamin92** [actionably/dashbot#45]
Hi guys - is this project still alive and actively maintained? There are a couple of very old pull requests and the project uses, meanwhile, older versions of libraries with known security vulnerabilities.

Any chance to get an answer?

Best regards,
Benni

**Comment by shotamakino** [comment]
Hi @mayrbenjamin92 , we are looking into rewriting much of this library. In the meantime, I see that you've made a pull request which I will merge in - thank you!
