### ISSUE TITLE
Cannot read property '$isSingleNested' of undefined

### ISSUE THREAD

**Issue by pqvst** [actionably/dashbot#5]
I suspect this is an issue with dashbot. I've been using version 0.6.2.
With the latest version (0.7.3) I get the following error:

    info: ERROR IN RECEIVE MIDDLEWARE: TypeError: Cannot read property '$isSingleNested' of undefined

**Comment by jhullfly** [comment]
Is this an issue we need to investigate? I see that you closed it.

**Comment by pqvst** [comment]
Nope, ignore it :) It was a mongoose issue
